name: .NET

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+'

jobs:
  Create_Speedseat_Release:

    runs-on: ubuntu-latest  
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Build Frontend
      run: |
        cd frontend
        npm ci
        npm run build --if-present

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build Backend
      run: |
        cd backend
        dotnet restore
        dotnet build --no-restore
        dotnet publish -c Release -o publish -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true -r win-x64
   
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      with:
        package-dir: 'frontend/package.json'
        allow-unknown: true
      id: Changelog
      env:
        REPO: ${{ github.repository }}
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        draft: false
        prerelease: false
        
    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./backend/publish/speedseat.exe
        asset_name: speedseat-win64.exe
        asset_content_type: application/octet-stream
